on:
  pull_request:
  push:
    branches:
      - "main"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
          version: 9
      - run: pnpm run typecheck
      - run: pnpm run lint
      - run: pnpm run format
      - run: pnpm run test
